name: GitHub Actions Build and Deploy linux-command
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: CheckOut
      uses: actions/checkout@master

    - name: Install and Build 
      run: |
        npm install
        npm run build

    - name: Deploy to Github gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: .deploy/

    - name: Setup Git Configuration
      run: |
        git config --global user.name "Xiechengqi"
        git config --global user.email "Xiechengqi01@gmail.com"

    - name: Add SSH Private Key
      run: |
         mkdir /home/runner/.ssh/
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
         chmod 600 /home/runner/.ssh/id_rsa
         ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts

    - name: Get Latest Commit Message
      run: |
        git log --pretty=format:"%s from Github Actions at `TZ=UTC-8 date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log

    - name: Deploy To Gitee Repo
      env:
        Gitee_Repo: gitee.com:Xiechengqi/linux-command.git
      run: |
        git clone git@${Gitee_Repo} .gitee_repo
        cd .gitee_repo
        git checkout -b master
        cd ../
        \cp -rf ./.deploy/* ./.gitee_repo/
        cd .gitee_repo
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "git@${Gitee_Repo}" master:master 

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: Xiechengqi
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: Xiechengqi/linux-command
